ERC725Alliance/erc725.js

.eslintrc
docs/source/content/api/api-decode-data.rst
docs/source/content/api/api-encode-all-data.rst
docs/source/content/api/api-encode-data.rst
src/index.ts
src/lib/utils.ts

Content created for the docs is now available as JSDoc.
This enables IDE to show documentation in the code.
I also added a few more TS types

Copy Docs content to JSDoc

---

src/index.ts
tsconfig.json

When a request made via **axios** fails, log the error and also print out the URL the request was sent to. This should simplify spotting a potential URL encoding problem especially when running a script via node.

chore(axios): add custom log message on error

---

package.json

Somehow there are still references to `axios` in the new package. 
We think it might be related to some old code in the build folder.

Ensure clean build folder when publishing to npm

---

package-lock.json
src/index.test.ts
src/lib/constants.ts
src/lib/encoder.test.ts
src/lib/encoder.ts
src/lib/utils.ts
src/types/ERC725JSONSchema.ts

Add missing types introduced in [LSP6](https://github.com/lukso-network/LIPs/blob/master/LSPs/LSP-6-KeyManager.md)
The `ERC725JSONSchema` interface does not support the latest `keyType` and `valueType`
The interface supports these new types
The lib should also be updated to encode/decode these types:
- #38 
Closes #39

Add support for bytes4 and bytes4[] + add tests

---

src/index.ts

bug fix for `fetchData()` return
Current types implies following return data:
```js
{
LSP3Profile: {
key: 'LSP3Profile', // string
value: { /* The profile itself */ } //any
}
}
```
But the return type of `fetchData()` is like this:
```js
{
LSP3Profile: {
LSP3Profile: {
name: 'Name',
description: '',
links: [],
tags: [],
profileImage: [Array],
backgroundImage: [Array]
}
},
'SupportedStandards:ERC725Account': '0xafdeb5d6'
}
```
Set return type to `any`
Reported by `void` on discord

fix: wrong return type for fetchData

---

src/index.test.ts
src/index.ts
src/lib/provider-wrapper-utils.ts
src/lib/utils.ts
src/providers/ethereumProviderWrapper.ts

Fix
If user requests a key which is not set in the ERC725Y contract, the function will throw
It will return '' or [] and won't throw
Closes #53

fix: handling of missing keys

---

src/index.test.ts
src/index.ts
test/mockProviders.ts

Fix
If we call fetchData on a JSONURL element with value null, it will throw. Because it will try to load data from non existing url. Cf issue #57 
Will simply return null instead of throwing.
Closes #57

fix: empty JSON url return null instead of crash

---

README.md
docs/getting-started.md
docs/writing-data.md
examples/src/fetchData.js
examples/src/getData.js
examples/src/instantiation.js
src/index.test.ts
src/lib/utils.test.ts
test/mockSchema.ts

Remove deprecated key `SupportedStandards:ERC725Account`.
The code sample use an old deprecated key in the schema and does not return anything for the key `SupportedStandards:`. 
Changed in:
- README
- md docs page
- js examples

docs: remove deprecated key `SupportedStandards:ERC725Account`

---

.github/workflows/bump-version.yml
.github/workflows/release.yml

CI update
- Tag is pushed on bump
- PR body of a release PR is not added to release notes
- Tag is added on merge to main
- Release PR body is added to release body

Change release ci

---

docs/classes/ERC725.md
src/index.test.ts
src/index.ts

feature
Adds encodeKeyName methods for encoding key names according to LSP2 JSONSchema standard https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md
Closes #74

feat: add encodeKeyName method

---

src/lib/schemaParser.test.ts
src/schemas/LSP3UniversalProfile.json
src/schemas/LSP4DigitalAsset.json
src/schemas/LSP5ReceivedAssets.json
src/schemas/LSP6KeyManager.json

- fixes in the ERC725Y JSON schemas (typos + deprecated content in keys)
- added an extra key for LSP4
In the ERC725Y JSON schemas, the `SupportedStandards:...` keys used `bytes` as their `valueType`,
This was changed in PR 54 in the LIPs repository: https://github.com/lukso-network/LIPs/pull/54
- fixed typo in LSP6 schema: `AddressPermissions:Permissions:<address>` -> `bytes32` (not ~`byte32`~)
- for `SupportedStandards:...` keys, use `bytes4` as their `valueType`.
- add `LSP4CreatorsMap:<address>` key in LSP4 schema

fix: update ERC725Y JSON Schemas to latest LSPs specs

---

docs/classes/ERC725.md
src/index.test.ts
src/index.ts

BREAKING CHANGE: if `fetchData` is called with a string, the output will be the value itself, not an object anymore.
Before:
```js
const dataOneKey = await erc725.fetchData('LSP3Profile');
/**
{
LSP3Profile: {
LSP3Profile: {
name: 'patrick-mcdowell',
links: [Array],
description: "Beautiful clothing that doesn't cost the Earth. A sustainable designer based in London Patrick works with brand partners to refocus on systemic change centred around creative education. ",
profileImage: [Array],
backgroundImage: [Array],
tags: [Array]
}
}
}
*/
```
after:
```js
const dataOneKey = await erc725.fetchData('LSP3Profile');
/**
{
LSP3Profile: {
name: 'patrick-mcdowell',
links: [Array],
description: "Beautiful clothing that doesn't cost the Earth. A sustainable designer based in London Patrick works with …
```

chore!: change fetchData output to non object

---

CHANGELOG.md
docs/classes/ERC725.md
docs/getting-started.md
docs/writing-data.md
src/index.test.ts
src/index.ts

the output of `getData` is not an object anymore, but the value directly if the input is a string.
Rename `schema` to `schemas`
Closes #127 
Closes #125 
We should update our tutorials accordingly.

feat!: change the output of getData for string input

---

docs/classes/ERC725.md
docs/classes/_category_.yml
docs/getting-started.md
docs/providers.md
docs/schemas.md
docs/writing-data.md

Split off from [docs PR166](https://github.com/lukso-network/docs/pull/166)
Includes:
- Overall grammar work
- applying unified styling
- adding tables for parameters/return values as we do in standard/contract sections
- fixed missing nav position
Explanation of using array[&nbsp;] instead of array[ ]:
Arrays are declared with spaces between brackets to improve clarity, but if you have more than one possible type or a small device, the second bracket gets split up with a line break. That's why we need to use the space symbol to always keep it as one object.
Already applied suggestions from Callum from PR166

docs grammar/styling overhaul

---

.mocharc.json
docs/classes/ERC725.md
src/index.test.ts
src/lib/utils.test.ts
src/lib/utils.ts

Closes #134 
Please check input/output data on the related issue.
The scope of the corresponding issue changed during the dev process - we will merge this as it already adds new features for the input and we will tackle the new output with issue: #140

`encodeData` should handle both named keys and hash keys

---

.eslintrc
docs/classes/ERC725.md
src/index.test.ts
src/index.ts
src/types/Method.ts

Improvement
Adds instance versions of `encodeKeyName` and `decodePermissions`, `encodePermissions`. Instance versions are available on an instance of ERC725 and call the static version directly.
Closes https://github.com/ERC725Alliance/erc725.js/issues/135

improvement: add instance versions of static methods

---

docs/classes/ERC725.md
docs/getting-started.md
docs/writing-data.md
schemas/LSP10ReceivedVaults.json
schemas/LSP12IssuedAssets.json
schemas/LSP3UniversalProfileMetadata.json
schemas/LSP4DigitalAsset.json
schemas/LSP5ReceivedAssets.json
schemas/LSP6KeyManager.json
schemas/LSP9Vault.json

- Fixes in the ERC725Y JSON schemas (after the LSP2Change [here](https://github.com/lukso-network/LIPs/commit/2d2c727956ad1fe0bcbb496e6719a626925b116b))
- Add Few extra Schemas (LSP9,LSP10,LSP6)
- Documentation update (old keys)
- Current behaviour is still according to the old version of LSP2.
- Change `Bytes20MappingWithGrouping` to `MappingWithGrouping`
- Change the constructing way of Mapping keys

refactor: update LSP Schemas according to LSP2 changes

---

README.md
docs/classes/ERC725.md
src/index.test.ts
src/lib/encodeKeyName.test.ts
src/lib/encodeKeyName.ts
src/lib/schemaParser.test.ts
src/lib/schemaParser.ts
src/lib/utils.test.ts
src/lib/utils.ts
src/types/ERC725JSONSchema.ts
test/mockSchema.ts

- Include the changes from #162 
- refactor!: remove old LSP2 Key Types (Bytes20..)
- fix failing tests
Closes #165 
Closes #163

refactor!: remove old LSP2 Key Types (Bytes20..)

---

docs/classes/ERC725.md
src/index.ts
src/lib/encodeKeyName.test.ts
src/lib/encodeKeyName.ts
src/lib/getSchemaElement.test.ts
src/lib/getSchemaElement.ts
src/lib/utils.test.ts
src/lib/utils.ts
src/types/dynamicKeys.ts
src/types/encodeData/JSONURL.ts

Related to #137 
Allowing the import of dynamic keys on class instantiation might break the `fetchData`/`getData` features.

feat: add dynamic keys support for `encodeData`

---

src/index.test.ts
src/lib/constants.ts
src/providers/ethereumProviderWrapper.ts
src/providers/web3ProviderWrapper.ts

Refactor?
This PR suggest a different versioning for ERC725Y interface IDs for the `constants.js` file.
In the file `constants.js`, the interface IDs do not provide context about which version of the [ERC725Y smart contract](https://github.com/ERC725Alliance/ERC725) they refer to.
The comments about the version refer to the [LUKSO smart contracts](https://github.com/lukso-network/lsp-smart-contracts/)
Suggest a different naming for these constants values, that reflect the versioning of the interface IDs changes based on the release of `@erc725/smart-contracts`

Suggest different version naming for ERC725Y interface IDs in `constants.js`

---

src/lib/provider-wrapper-utils.ts
src/providers/ethereumProviderWrapper.ts
src/providers/web3ProviderWrapper.ts
src/types/JsonRpc.ts

Fixes issue where data cannot be fetched from l16 closes #193 
eth_call specs are different from what was implemented:
- Added 'latest' tag
- Removed gasPrice so call does not fail with gas error
Tested and this now works with both l14 and l16
https://github.com/ethereum/go-ethereum/issues/21108
https://www.quicknode.com/docs/ethereum/eth_call

Update JsonRpc eth_call parameters

---

src/index.test.ts
src/index.ts

Adds support for dynamic parts for `encodeKeyName` function. 
Dynamic Parts variable was not exposed to public function call
Closes #213

feat: expose dynamic parts to public encodeKeyName

---

schemas/LSP6KeyManager.json

Bug 
Incorrect `valueType` and `valueContent` in `AddressPermissions:AllowedERC725YKeys` permission, update to correct values as specified in docs https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-6-KeyManager.md#addresspermissionsallowederc725ykeysaddress

Incorrect valueType in LSP6KeyManager.json

---

src/lib/decodeData.test.ts
src/lib/utils.test.ts

fix
Change the reference of old LSP7 interface id  to a random value as it is not relevant for the tests.
- `0xe33f65c3` to `0xdeadbeef`

fix: Change the reference to old LSP7 interface id to a random value

---

src/index.ts
src/lib/getData.ts
src/types/Config.ts

This PR is *one of the first overhauls* to resolve internal issues that were faced when adding functionality to this tool library. 
At the moment, most of the functionality comes directly from the ERC725 class file, that can not be used from the library or the other way around. Each public function should have its own library files for tests and methods that only get called/integrated into the class (`index.ts`) later.

Reconstruct getData as modular library function

---

src/index.ts
src/types/decodeData.ts

Fix the type of the object returned by fetchData function.
When fetching profile `await erc725.fetchData("LSP3Profile")` expects that it will return `DecodeDataOutput` with `value` field. But value is typed as `string | string[] | URLDataWithHash` while in `value`  I get profile object
```
{
LSP3Profile: 
{...}
}
```
[Link to open issue](https://github.com/ERC725Alliance/erc725.js/issues/192)
A new type `FetchDataOutput` was created with the following properties :
```
FetchDataOutput {
value:
| string
| string[]
| { LSP3Profile: Record<string, any> }
| Record<string, any>;
name: string;
key: string;
}
```

Fix return type for `fetchData`

---

src/lib/encodeKeyName.test.ts
src/lib/encodeKeyName.ts

bug fix
uint type takes only decimals
uint type can take hex and decimals
N/A

fix: Encode key name should parse any number (hex or decimal) for uint type

---

src/types/ERC725JSONSchema.ts

Minor refactoring.
`'Mapping'` was mentioned twice.
```js
export type ERC725JSONSchemaKeyType =
...
| 'Mapping'
...
| 'Mapping'
...
```

fix: removed ERC725JSONSchemaKeyType duplicate value

---

CHANGELOG.md
package-lock.json
package.json

- removed ERC725JSONSchemaKeyType duplicate value ([060ee6c](https://github.com/ERC725Alliance/erc725.js/commit/060ee6ce23bda328f727140419de7590f48fc394))
- wrong web3 import ([337269e](https://github.com/ERC725Alliance/erc725.js/commit/337269eb22f82e6f44f9b8c9be4840fa6cd676ed))

chore(release): 0.17.2

---

schemas/LSP1UniversalReceiverDelegate.json
schemas/LSP3UniversalProfileMetadata.json
schemas/LSP5ReceivedAssets.json
schemas/LSP6KeyManager.json
schemas/LSP9Vault.json

- removed ERC725JSONSchemaKeyType duplicate value ([060ee6c](https://github.com/ERC725Alliance/erc725.js/commit/060ee6ce23bda328f727140419de7590f48fc394))
- wrong web3 import ([337269e](https://github.com/ERC725Alliance/erc725.js/commit/337269eb22f82e6f44f9b8c9be4840fa6cd676ed))

Release v0.17.2

---

package.json
src/lib/detector.test.ts
src/lib/detector.ts

Introduce a new function described in #285 to allow easy detection of which permission is present, supporting plain bytes32 or literal permissions.

feat: Add checkPermissions function

---

docs/classes/ERC725.md

Fix example in library docs where the methode `encodeData` takes an object directly ❌ instead of an array of objects ✅

docs: fix missing array square brackets for encodeData

---

docs/classes/ERC725.md

In the docs, all the examples are one after the other, making the code snippets very long and big.
- Sort them between toggles that can be opened, so that it is easier to find the relevant example for the developer.
- Improve subheadings so that examples can be more easily found from the sidebar

docs: use toggles to display better examples of encoding

---

package-lock.json
package.json
src/lib/encoder.ts

Let's save [18.2kb](https://bundlephobia.com/package/bignumber.js@9.1.1) as this feature is already included in [web3-utils](https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#bn)

chore: use web3-utils instead of bignumber.js

---

docs/classes/ERC725.md
src/index.test.ts
src/index.ts

- refactor: expose `checkPermissions` function
- docs: add code example for `checkPermissions` function
- test: check if the function is exposed correctly on the instance and the class
PR related is: https://github.com/ERC725Alliance/erc725.js/pull/286/
Exposing the checkPermissions function
Links:
PR: https://github.com/ERC725Alliance/erc725.js/pull/286/
Original issue: https://github.com/ERC725Alliance/erc725.js/issues/285

refactor: expose `checkPermissions` function

---

.github/workflows/release.yml
RELEASE.md

CI
Current release CI is broken and requires manually editing CHANGELOG
1. Merge develop into main.
2. Release Please will create the release PR going to main.
3. Merge the generated release PR.
4. Package will be published to NPM.
the first time a new release is run the CHANGELOG will still need to be manually updated, this is because the way the previous CI did things broke the CHANGELOG for the _next_ release. After this the CHANGELOG should be running correctly again

ci: add release please workflow

---

schemas/LSP17ContractExtension.json
schemas/LSP8IdentifiableDigitalAsset.json

feature
There is no schemas for LSP8
Create `LSP8IdentifiableDigitalAsset.json` file with all the ERC725Y data keys of LSP8.
Also created a single file for the LSP17 data key (although it is also present in LSP3 json schema file).

feat: add schemas for LSP8 + LSP17

---

schemas/LSP10ReceivedVaults.json
schemas/LSP12IssuedAssets.json
schemas/LSP3ProfileMetadata.json
schemas/LSP4DigitalAsset.json
schemas/LSP5ReceivedAssets.json

🐜 Bug Fix
The schemas for the `...Map` value in the tuple mention `bytes8`. But this was changed to `uint128`.
See following PRs in LIP repos for reference:
- https://github.com/lukso-network/LIPs/pull/173
- https://github.com/lukso-network/LIPs/pull/233
Correct the schemas with the right value type in the tuple.

fix: incorrect value in schema for array length in `...Map`

---

schemas/LSP6KeyManager.json

FIx: Update LSP6 schema valueType and valueContent

fix: update lsp6 schema

---

src/lib/decodeData.ts

**Refactor**
Current code base work fine, but not easy to understand the code behind the tuple logic.
Improve the code for tuple checking by create internal methods to valid and extract tuple content.

refactor: improve code for tuple checks

---

src/lib/decodeData.ts
src/lib/encoder.test.ts
src/lib/encoder.ts
src/lib/utils.ts
src/types/ERC725JSONSchema.ts

**New feature**
Currently, erc725.js allows to encode only numbers `valueType` of `uint128` or `uint256`.
Any other type available in the 8 bit range from Solidity are not available.
Refactor the value type map to filter by regex and allow to encode number from `uint8` to `uint256`.

feat: add support to encode / decode any `uint8` to `uint256` types

---

docs/classes/ERC725.md
src/constants/interfaces.ts
src/index.test.ts
src/index.ts
src/lib/detector.test.ts
src/lib/detector.ts

This reverts commit ab83f0839457addfb3a03f0925b2f24a67743f79.
Reverts: https://github.com/ERC725Alliance/erc725.js/pull/352
The reason to remove the function was that:
- the interface ID get outdated fast
- and it is better to ask user to do the normal "erc165" way to check interface
See conv: https://github.com/ERC725Alliance/erc725.js/pull/317
However, these interface IDs will be modified less and less in the future.
At this stage, it is too early to remove this function for the next release.

Revert "refactor!: remove supportsInterface"

---

src/constants/constants.ts
src/lib/encoder.test.ts
src/lib/encoder.ts

Add workaround to read old (bytes4,URI) as a VerifiableURI without verification.
Allow 0x00000000 verification everywhere and don't convert it to unknown
Pass unknown verification signatures back.
Both 0x00000000 and unknown turn into "unknown" making it impossible to create third party verification methods while using erc725.js
We were unable to read the old (bytes4,URI) for LSP8TokenMetadataBaseURI
LSP8TokenMetadataBaseURI is converted and returns as VerifiableURI information.
Saving and retrieving an unknown verification methods is now possible with getData
The 0x00000000 method is now defined as a constant as well.

fix: Add workaround to read (bytes4,URI), repair unknown signature to pass.

---

src/index.test.ts
src/lib/decodeData.test.ts
src/lib/encoder.test.ts
src/lib/encoder.ts
src/lib/getDataFromExternalSources.ts
src/lib/provider-wrapper-utils.ts
src/provider/providerWrapper.ts
src/types/JsonRpc.ts

- fix: Repair problems with IPFS, fetch and VerifiableURI
- fix: Repair to not throw errors when data is not authentica or not accessible withing getDataFromExternalSources.
The current behavior is that when data is invalid or unreachable in ipfs. getDataFromExternalSource will throw an exception.
These are now converted to a console.error, allowing the data to return as "null". This allows getData to be called with multiple keys
including one that maybe invalid and not just throw out of the section of code.
I also made a similar kind of fix when the array length data (i.e. LSP12IssuedAssets[]) contains a uint256 instead of a uint128.

fix: Make data retrieval more resilient. Do not throw on ipfs data problems.

---

README.md
docs/getting-started.md

Update the docs
Currently throwing errors for TS users that are unaware of built-in types.
They instantiate their schemas with the `ERC725JSONSchema[]` type.

docs: Add TypeScript to getting started page

---

docs/schemas.md
src/index.test.ts
src/schemas/index.ts
src/types/ERC725JSONSchema.ts

Feature + Bug fix
Currently when importing a schema from the `schemas/` folder, the typing breaks in Typescript projects. See the following error:
In order to fix that, the project has to import the `ERC725JSONSchema` type and cast it with `as`.
```ts
import ERC725, { ERC725JSONSchema } from '@erc725/erc725.js';
import LSP6Schema from '@erc725/erc725.js/schemas/LSP6KeyManager.json';
// instantiate erc725.js
const erc725js = new ERC725(LSP6Schema as ERC725JSONSchema[]);
```
- Fix the problem above by add the `string` type to `keyType` property in `ERC725JSONSchema` type.
- Allow shorter imports by exporting all the available schemas from the `schemas/` folder. This enables to import typed schemas from the `schemas/` folder as shown below (instead of having to write multiple `import` …

feat: allow to import TS typed schemas from `@erc725/erc725.js/schemas`

---

docs/classes/ERC725.md
src/index.test.ts
src/lib/encoder.test.ts
src/lib/utils.test.ts
src/lib/utils.ts
src/types/decodeData.ts

**Feature**: Dynamically encode ERC725 storage keys of type **Array**.
The library only allows users to define the full array they want to encode and set to a contract. For updates, developers must read through all existing elements and pay the gas for re-setting elements in the list, even if only a few of them are actually updated. This is highly impractical. 
Within the **encodeData(...)** function, developers can define a **startingIndex** and an **arrayLenght** parameter to dynamically adjust the output, which can be used for more gradient storage updates. Both parameters are optional. If not provided, the encoding falls back to the default behavior as before, starting from index 0 and using the length of the provided elements in the array.

feat: add dynamic array encoding for encodeData

---

src/lib/getDataFromExternalSources.ts

Allow JSON detection to work if there is a LF right before and after the end.

fix: Allow LF or TAB in the middle of JSON detection

---

src/lib/schemaParser.test.ts
src/lib/schemaParser.ts

Feature ⭐ 
Currently, the function `getSchema` returns `?????` in the dynamic part for Mapping key type.
Change this behaviour so that dynamic part of data keys are replaced by the hex value in the name, when dynamic part is something such as `<address>` or `<bytes32>`

feat: replace dynamic part with hex value when parsing schemas for `Mapping` keys

---

biome.json
src/lib/utils.ts

Some lint errors removed.
No real code changes.

fix: Found some small lint problem combing through with biome

---

CHANGELOG.md
biome.json
package-lock.json
package.json
src/index.test.ts
src/index.ts
src/lib/detector.test.ts
src/lib/detector.ts
src/lib/encoder.test.ts
src/lib/getDataFromExternalSources.ts
src/lib/permissions.ts
src/types/Method.ts
src/types/provider.ts

Filter out keys from LSP6_DEFAULT_PERMISSIONS because it now has ALL_PERMISSIONS.
Having ALL_PERMISSIONS set during encodePermissions will always return ALL_PERMISSIONS.
Currently calling decodePermissions will always return ALL_PERMISSIONS on.

fix: Filter out ALL_PERMISSIONS from keys in LSP6_DEFAULT_PERMISSIONS.

---

src/index.ts
src/lib/encoder.ts

:star:
Currently, there are no methods available in the ERC725 class for:
- encoding / decoding value Content
- encoding / decoding JSONURL or VerifiableURI
This is useful for tools like ERC725-inspect, lsp-utils, or services like indexers to easily decode data from logs / fetched from contracts, or prepare data easily without requiring a full schema.
Add the following methods:
- `encodeDataSourceWithHash(...)`
- `decodeDataSourceWithHash(...)`
- `encodeValueContent(...)`
- `decodeValueContent(...)`
available to be imported individually like this:
```js
import { encodeDataSourceWithHash } from "@erc725/erc725.js"
```
or from the ERC725 class (as static methods or accessible in an instance).

feat: export methods for encoding/decoding dataSourceWithHash and valueContent

---

biome.json

Biome will find different formatting in package.json due to the release-please
update and the merge to main and then release chore will fail.
Ignore formatting inside of package.json

fix: Ignore package.json formatting in biome

---

.github/workflows/release.yml

Release-As: 0.25.0
Remove the outdated version check step and use the release-please output instead.

ci: change version change check in release workflow + re-trigger release commit 

---

src/index.test.ts
src/lib/encoder.test.ts
src/lib/encoder.ts
src/lib/utils.test.ts
src/lib/utils.ts
test/mockSchema.ts

⭐ Feature
🐛 Bug Fix
**Bug**
When encoding `uintN` in tuples and the `valueContent` is `Number`, these are always encoded to a `uint256` as a 32 bytes long value because of the following line in the code:
https://github.com/ERC725Alliance/erc725.js/blob/06d872baa75fb3bfaac3e51c541e727eb76646e7/src/lib/encoder.ts#L675-L690
**Missing Feature**
Additionally, there is only support for few `bytesN` types, like `bytes2`, `bytes4`, `bytes8`, etc...
This the padding for the encoding of uintN and bytesN + add support for multiple `bytesN`

feat: add support for encoding `bytes1` to `bytes32` + fix incorrect encoding `uintN`

---

src/index.ts
src/lib/encodeKeyName.ts
src/lib/schemaParser.test.ts
src/lib/schemaParser.ts
src/types/ERC725JSONSchema.ts

:star: Feature
#400 introduced a change in the `getSchema` function that replaces the dynamic part `<...>` with the actual hex value in the `name` of the schema.
However, this causes a problem has the schem returned cannot be used anymore as it will the `name` now contains a hex value and `ERC725.encodeData` or `ERC725.decodeData` will not find the name anymore when searching through the data keys.
None

feat: add `dynamicName` in schema returned by `getSchema`

---

src/lib/decodeData.test.ts
src/lib/decodeData.ts

⭐ Feature
When using `decodeData` with key type Array, only arrays `[ ... ]` can be returned.
Allow to use `decodeData` with key type Array that allows to pass a a 16 bytes long value, that will be decoded as a number.
```js
const decodedData = ERC725.decodeData(
{
keyName: 'LSP12IssuedAssets[]',
value: '0x00000000000000000000000000000003',
},
[
{
name: 'LSP12IssuedAssets[]',
key: '0x7c8c3416d6cda87cd42c71ea1843df28ac4850354f988d55ee2eaa47b6dc05cd',
keyType: 'Array',
valueContent: 'Address',
valueType: 'address',
},
],
);
```
will output:
```
// decodedData {
//  key: '0x7c8c3416d6cda87cd42c71ea1843df28ac4850354f988d55ee2eaa47b6dc05cd',
//  name: 'LSP12IssuedAssets[]',
//  value: 3
// }
```

feat: allow to decode array length only as number using `decodeData`

---

src/index.test.ts
src/types/encodeData/JSONURL.ts

🌟 Feature
Current when encoding parts in tuples that are `uintN`, it is not possible to pass a plain `number`. The number always needs to be encoded as hex first, as tuples only accept `string` type.
Fix this behaviour by allowing to pass `number` for encoding.
Closes #393

feat: allow to pass `number` directly in array when encoding tuples

---

docs/methods.md

See PRs from docs.lukso.tech for reference: https://github.com/lukso-network/docs/pull/993/files

docs: add missing code sandbox from docs.lukso.tech

---

src/lib/encoder.ts
src/lib/utils.test.ts

This reverts commit 3e6213a3acf3b5d16b79447f87a7029f1020d7b3.

Revert "refactor: improve code for `Literal` hex for `valueContent`" to return `null` when decoding

---

src/index.test.ts
src/index.ts
src/lib/decodeData.test.ts
src/lib/decodeData.ts
src/lib/decodeMappingKey.test.ts
src/lib/decodeMappingKey.ts
src/lib/encodeKeyName.test.ts
src/lib/encodeKeyName.ts
src/lib/getSchemaElement.test.ts
src/lib/getSchemaElement.ts
src/lib/schemaParser.test.ts
src/lib/schemaParser.ts
src/lib/utils.test.ts
src/lib/utils.ts
src/types/ERC725JSONSchema.ts
src/types/decodeData.ts
test/mockSchema.ts
test/testHelpers.ts

- **Merge pull request #383 from ERC725Alliance/fix/upgrade-modules**
- **fix: Some cleanup, remove global-agent, some new minor upgrades**
- **Update src/lib/encodeKeyName.ts**

fix: Try to work on tests on top of upgrades

---

docs/methods.md
src/lib/utils.test.ts

Partially addressing #279 
Based on the same updated example in the docs for https://github.com/lukso-network/docs/pull/1091

docs: add documentation on how to decode tuple of CompactBytesArray with `AddressPermissions:AllowedCalls:<address>` as example

---

docs/methods.md

Docs fix
The docs page section for `decodeData` with tuples of CompactBytesArray show an example that is incorrect. The nested arrays are not wrapped into an array.
Fix the example output in the docs by adding the extra `[ ... ]` missing around the nested arrays.

docs: fix incorrect docs for result of decoding tuple of CompactBytesArray

---

src/index.test.ts

- Remove requirement for npm run build from npm run test.

fix: Remove build dependency from npm run test

---

docs/getting-started.md
docs/methods.md

Docs update
Missing a few methods in documentation
Added these missing methods
This PR adds missing methods as well as adds a redirect to ERC725 Inspect tool in docs section

docs: add methods to docs + erc725 inspect redirect

---

docs/schemas.md

fix: new doc redirects for trailing slash flag

---

src/lib/schemaParser.test.ts
src/lib/schemaParser.ts

The `getSchema` function has a bug when retrieving schemas of key type `Array`. It reads the last 16 bytes and does not convert correctly from hex to decimal .
See the screenshot below, where the array index in `dynamicName` should be `35` ✅ and not `23` ❌

fix: decode array indexes correctly from hex to number in `dynamicName` returned by `getSchema`
