ERC725Alliance/erc725.js

README.md, package-lock.json, package.json, src/index.js, test/test.js
Added fetching of assets and JSON files and comparing hashes
=> fetch-data

package-lock.json, src/index.ts
Improving support for interoperability between common JS, and ES modules.
=> Adding named export

.eslintrc, .gitignore, .mocharc.json, package-lock.json, package.json, src/lib/constants.ts, src/lib/encoder.ts, src/lib/queries.ts, src/lib/utils.ts, test/test.ts, tsconfig.json, tsconfig.module.json
- provide two builds (commonjs & esm)
- removed unnecessary dependencies
- replaced @apollo/client with graphql-tag
- updated a few imports to allow treeshaking later on
- added mocha config file
- resolved all the issues of "npm audit"
=> Optimize Build

README.md, docs/source/content/getting-started.rst, src/index.ts, src/lib/encoder.ts, src/lib/utils.ts, src/types/Config.ts, test/test.ts, test/testHelpers.ts, tsconfig.json
For review purposes it's best to look at the commits individually.
=> Adjust configuration and extend tree-shaking support

docs/writing-data.md
Docs
Add missing sidebar label in Writing Data docs
=> docs: add missing sidebar label to write data docs

src/providers/ethereumProviderWrapper.ts, src/providers/web3ProviderWrapper.ts, src/types/JsonRpc.ts, test/mockProviders.ts
Performances
See issue #49 
Will use only 1 RPC call when possible
Closes #49
=> perf: use one RPC call on getData multiple

package.json
=> chore: auto generate and commit docs when release

package-lock.json, package.json
Fixed the docs script and remove auto generated docs
=> docs: remove docs generation on bump

package-lock.json, package.json
=> Develop to main

docs/classes/ERC725.md, src/index.test.ts, src/index.ts, src/lib/schemaParser.test.ts, src/lib/schemaParser.ts, src/schemas/LSP3UniversalProfile.json, src/schemas/LSP4DigitalAsset.json, src/schemas/LSP5ReceivedAssets.json, src/schemas/LSP6KeyManager.json, src/schemas/index.ts
Closes #79 
There is no dynamic or remote import of the LSP schemas. I hope it won't add too much size in the lib. If the "repository" of schemas grows, we will need to find a more optimised way to load these schemas.
It also refactor the docs.
=> feat: add getSchema

src/lib/schemaParser.test.ts, src/lib/schemaParser.ts
=> fix: getSchema array

src/schemas/LSP1UniversalReceiverDelegate.json, src/schemas/LSP4DigitalAssetLegacy.json, src/schemas/index.ts
=> Add LSP1 and LSP4 legacy

.github/workflows/release.yml, RELEASE.md
Updates release CI and release docs:
Stores release notes in env var so that a multi line PR body does not break CI
=> ci: improve release CI and docs

docs/classes/ERC725.md, src/index.test.ts, src/index.ts, src/lib/constants.ts, src/lib/isValidSignature.ts, src/providers/ethereumProviderWrapper.ts, src/providers/web3ProviderWrapper.ts, src/types/Method.ts, test/mockProviders.ts
=> feat: isValidSignature

docs/schemas.md
To reflect these changes:
https://github.com/lukso-network/docs/commit/9f737cf7f32d0bbfe5d3e056c5cc9419fad56a07
=> docs: update schemas page

docs/classes/ERC725.md
=> docs: reorder functions in docs

docs/classes/ERC725.md, src/index.test.ts, src/lib/utils.test.ts, src/lib/utils.ts
Improvement
Changes result structure of object returned from `encodeData` to just contain keys and values.
Updated tests + add case for encoding multiple keys. Updated docs. Closes https://github.com/ERC725Alliance/erc725.js/issues/140
Before: 
```javascript
erc725.encodeData({
LSP3Profile: {
hashFunction: 'keccak256(utf8)',
hash: '0x820464ddfac1bec070cc14a8daf04129871d458f2ca94368aae8391311af6361',
url: 'ipfs://QmYr1VJLwerg6pEoscdhVGugo39pa6rycEZLjtRPDfW84UAx',
},
});
/**
{
LSP3Profile: {
value:
'0x6f357c6a820464ddfac1bec070cc14a8daf04129871d458f2ca94368aae8391311af6361696670733a2f2f516d597231564a4c776572673670456f73636468564775676f3339706136727963455a4c6a7452504466573834554178',
key: '0x5ef83ad9559033e6e941db7d7c495acdce616347d28e90c7ce47cbfcfcad3bc5',
},
}
*/
```
After: 
```javascript …
```
=> improvement!: change encodeData result structure

tsconfig.json
Closes #141 
Please merge #148 before
=> chore: enable sourceMap

docs/classes/ERC725.md, src/lib/encodeKeyName.test.ts, src/lib/encodeKeyName.ts
Closes #161
~~Merge #167 first~~
=> feat: add dynamic keys for encodeKeyName

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 0.13.0

.eslintrc, docs/classes/ERC725.md, examples/src/instantiation.js, package-lock.json, package.json, src/index.test.ts, src/index.ts, src/lib/utils.test.ts, src/lib/utils.ts, src/types/decodeData.ts
=> feat: add dynamicKeys for decodeData

src/index.ts, src/lib/getDataFromExternalSources.test.ts, src/lib/getDataFromExternalSources.ts, src/lib/utils.ts
=> fix: don't throw on null jsonurl/asseturl

examples/package-lock.json, examples/package.json, examples/src/decodeData.js, examples/src/encodeData.js, examples/src/fetchData.js, examples/src/getData.js, examples/src/instantiation.js
=> docs: update examples scripts

schemas/LSP12IssuedAssets.json, src/lib/decodeData.test.ts, src/lib/decodeData.ts, src/lib/encodeKeyName.ts, src/lib/encoder.ts, src/lib/utils.test.ts, src/lib/utils.ts, src/types/ERC725JSONSchema.ts
Closes #181 
--
Need to do: #46 before
=> Add tuple encoding/decoding

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 0.14.2

README.md, docs/getting-started.md, docs/providers.md
update docs to use l16 rpc url
=> docs: switch rpc url in docs to l16

schemas/LSP4DigitalAsset.json
=> fix: LSP4Creators[] valueType

docs/getting-started.md, docs/schemas.md
Initially from:
https://github.com/lukso-network/docs/pull/339
=> docs: reorder valueType and valueContent

CHANGELOG.md, package-lock.json, package.json
Bump version to v0.15.0
* add LSP6 `ENCRYPT` permission in for encrypt/decrypt permissions methods. (#223)
=> chore(release): 0.15.0

src/index.test.ts, src/index.ts
=> feat: make library compatible with RPC urls

docs/getting-started.md, docs/providers.md
To sync with: https://github.com/lukso-network/docs/pull/434
=> docs: update docs

src/lib/decodeMappingKey.ts
Closes https://github.com/ERC725Alliance/erc725.js/issues/280
=> fix: wrong web3 import

src/constants/interfaces.ts, src/index.test.ts, src/lib/detector.test.ts, src/lib/detector.ts
- refactor: change 0.7.0 interfaceId to 0.10.2
>Old interfaceId were removed
=> refactor: change 0.7.0 interfaceId to 0.10.2

README.md, docs/classes/ERC725.md, docs/getting-started.md, docs/schemas.md, examples/src/fetchData.js, examples/src/instantiation.js, package-lock.json, package.json, schemas/LSP10ReceivedVaults.json, schemas/LSP12IssuedAssets.json, schemas/LSP17ContractExtension.json, schemas/LSP3ProfileMetadata.json, schemas/LSP4DigitalAsset.json, schemas/LSP5ReceivedAssets.json, schemas/LSP8IdentifiableDigitalAsset.json, src/index.test.ts, src/index.ts, src/lib/encodeKeyName.test.ts, src/lib/encoder.ts, src/lib/schemaParser.test.ts, src/lib/utils.test.ts, src/schemas/index.ts, test/mockSchema.ts
docs.lukso.tech sync the latest changes in the `docs/` folder from the `main` branch.
Update the `main` branch without releasing, so that docs.lukso.tech can update the erc725.js changes automatically.
=> Update main branch to sync latest docs

docs/schemas.md
Cherry-pick commit from main
Commit went directly into main
=> fix: Cherry pick commit from main

docs/classes/ERC725.md
For compatibility with: https://docusaurus.io/blog/releases/3.0
Related to: https://github.com/lukso-network/docs/pull/711
=> docs: upgrade docs so they work with mdx3

README.md, docs/getting-started.md
Improve the README and remove early stage notice
=> docs: update README and docs

schemas/LSP4DigitalAsset.json, schemas/LSP8IdentifiableDigitalAsset.json
Implement updates from v0.14.0
=> chore: update schemas with latest LSP8 specs

package.json, src/index.ts, src/provider/providerWrapper.ts, src/types/Method.ts
Add missing type exports at the root.
Fix some lint errors brought up by biome.
=> fix: Export some missing types and make some lint fixes.

package-lock.json, src/constants/constants.ts, src/index.test.ts, src/index.ts, src/lib/decodeData.test.ts, src/lib/decodeData.ts, src/lib/decodeMappingKey.ts, src/lib/encodeKeyName.test.ts, src/lib/encodeKeyName.ts, src/lib/encoder.test.ts, src/lib/encoder.ts, src/lib/isValidSignature.ts, src/lib/schemaParser.test.ts, src/lib/schemaParser.ts, src/lib/utils.test.ts, src/lib/utils.ts, src/provider/providerWrapper.ts, src/types/ERC725JSONSchema.ts, src/types/decodeData.ts, src/types/dynamicKeys.ts, src/types/encodeData/JSONURL.ts, test/mockSchema.ts, test/serverHelpers.ts
Upgrade to viem and bigint for the main implementation.
=> feat: Upgrade to viem and bigint

docs/methods.md, docs/schemas.md
docs update, fixes the prettier and redirect issues
=> fix: prettier + redirects
